### ISSUE TITLE
No Resource

### ISSUE THREAD

**Issue by JuanPionero** [devin-la/ionic-video-chat-v2-issues#110]
I have just purchased Video and Text Chat (v2)
After execute the npm install, I tried setting ionic cordova platform add ios, and 
I received a Error message:

Adding ios project...

Creating Cordova project for the iOS platform:

	Path: platforms/ios
	Package: com.ionicvideochat.v3
	Name: ionic-video-chat-3
iOS project created with cordova-ios@4.5.3

Error: Source path does not exist: resources/ios/icon/icon-small@2x.png

Could you help me, please?

**Comment by whatnowangga** [comment]
you just add your icon
and do `ionic resources`

**Comment by JuanPionero** [comment]
I have it now all transpiled, compiled and tested in both type devices android and ios.
Thanks so much.
