### ISSUE TITLE
Application "not found" in Heroku

### ISSUE THREAD

**Issue by lisaiceland** [devin-la/ionic-video-chat-v2-issues#62]
Hi.
I have setup the app completely and I'm running other node.js servers successfully testing as well. 

After I set up your server with no changes, except the mongo info and connect with the MONGODB_URI and deployed, I'm getting an application error if I run on the FREE plan $0 and if I change to Hobby ($7), I/m getting a "not found" error.

Error atatched and build log attached.
![screen shot 2017-03-19 at 8 44 54 pm](https://cloud.githubusercontent.com/assets/3590486/24086870/1aa69a38-0ce5-11e7-8e7e-8322a1abbd01.png)

-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x via semver.io...
       Downloading and installing node 6.10.0...
       Using default npm version: 3.10.10
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json)
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 19.2M
-----> Launching...
       Released v28
       https://chatscape360socketserver.herokuapp.com/ deployed to Heroku

**Comment by arzynik** [comment]
There is nothing to see via urls. It looks like you have the socket server setup fine. 

Enter that URL into your config.ts file on your app and it should be able to connect.

Also there should be no difference between free and hobby teir. But because free turns off after inactivity, it's probably better to stay on hobby while developing.

**Comment by lisaiceland** [comment]
Ok thnx got it but still I'm NOT able to run this.
A.
1. I see you have an express server that looks like it should be booting with the app, in my case it's on heroku. ok. Can you tell me what's purpose of this architecture, is it to load the server to keep the socket open a app end constantly?
2. Second,  I'm pointing the app config.ts setting to the server that is also running on heroku with the mongoLab mongodb. 
This does not work for me.

B. 
1. I'm trying straight with local settings with npm install on both client and server:
2. run mongod. ok.
3. run the chat-server connecting to the local mongodb. ok.
4. ionic serve the app with local urls and it's still not working. 

I've created and run many Ionic 2 projects, this is just weird.

Can you tell me the steps you'e running on the build that you have updated last how you're doing it please. Steps is what I need to replicate and make sure I'm not missing something. I thought I was covering all the steps. Maybe I missed something.
Thnx.

**Comment by arzynik** [comment]
All communication between the app and server happen over socket.io. This includes logging in, signing up, sending messages, and initiating video calls.

What does not work for you? Please be specific and provide screenshots.

What about it is not working on the local settings?

Absolutely all steps required to build, setup, and run are provided in the wiki https://github.com/devin-la/ionic-video-chat-v2-issues/wiki/Setup

**Comment by lisaiceland** [comment]
1. Ok very kool I got the app hitting the Heroku server and I can create a login and create the user in mLab. I see it in the users collections. Done. I'm going to get the AWS net. Seems pretty straight-forward.

2. I'm having an issue with the iOs build. I have looked a the iosrtc doc and made sure the setting was there in the config.xml and ran the chmod as well and then tried to build the iOS and keep on getting this weird error, attached. 

![screen shot 2017-03-20 at 12 45 19 pm](https://cloud.githubusercontent.com/assets/3590486/24114055/dddf4892-0d6c-11e7-9f55-f4b5ce4f716d.png)

3. I haven't tried the Android build yet. Will do that last.

**Comment by arzynik** [comment]
i dont know the real reason this error shows up sometimes in cordova/ionic, but the best way for me to deal with it is:

```
ionic platform remove ios
ionic platform add ios
```

**Comment by lisaiceland** [comment]
tried everything from stack, your recommendations. Plz help me on this. Thnx so much!

**Comment by arzynik** [comment]
Are you still experiencing the cdvviewcontroller issue? 

It doesn't have anything to do with this app specifically. You best bet would be to check stackoverflow and get help there.

**Comment by lisaiceland** [comment]
yes exactly it is. That's what I thought.

I've looked in SO but nothing seems to resolve this. Weird.

**Comment by arzynik** [comment]
you might also try updating your global install of cordova or ionic using npm

**Comment by lisaiceland** [comment]
I tried thta.

I think from all the forum chatter...it's a bug that's showing up on Xcode 8. So, I'm downloading 7.3.1 and see what I get.

**Comment by lisaiceland** [comment]
OK figured it out!

**Comment by arzynik** [comment]
great! feel free to post your solution here in case it can help other people.
