### ISSUE TITLE
Video chat not available

### ISSUE THREAD

**Issue by atn2017** [devin-la/ionic-video-chat-v2-issues#63]
I am probably not using it correctly, but I cannot seem to get to the video chat option. I see image attachment option and text chat only. I am currently testing with 'ionic serve --lab' option only.

What am I missing?

**Comment by arzynik** [comment]
On the contact list, press and hold the contact to display the modal to call.

**Comment by atn2017** [comment]
Oh, yes, I missed it somehow. It is throwing an id error, but I will see what is causing it now that I can start the video chat. Thanks!

**Comment by arzynik** [comment]
@atn2017 see if https://github.com/devin-la/ionic-video-chat-v2-issues/issues/61 helps you. i havent been able to confirm this yet, but it may help you.
