### ISSUE TITLE
Feature/Roadmap Timeline

### ISSUE THREAD

**Issue by afeezaziz** [devin-la/ionic-video-chat-v2-issues#64]
Hi @arzynik ,

Thanks for making this starter package. I see that there is a lot features that you would like to continue to add to this package. Do you have a timeline or perhaps priority which feature is going to be implemented first?

Thanks!

**Comment by arzynik** [comment]
There isnt really a hard timeline. Just trying to get to them as I have time.

Feel free to request anything you want, or add a +1 to any of the issues you want, and i can try to prioritize them.

I thought it might be cute to do something like https://www.codefund.io/view.php?id=11, where anyone can contribute to the dev by helping fun it more, but I doubt that will go anywhere.
