### ISSUE TITLE
Echo

### ISSUE THREAD

**Issue by orouwk** [devin-la/ionic-video-chat-v2-issues#67]
1. Do you know how can I remove the echo during a call? it's quite annoying.
Is it hardware related? I'm using two android phones for testing.
2. Also the connection is not upgrading to websocket and it keeps pulling the server.
I'm doing the server side testing on Pivotal CloudFoundry.
tks

**Comment by arzynik** [comment]
1. What echo? Are you using both devices in the same room? I have tested with desktop, android, iphone, and ipad, and haven't ran into any echos yet.
2. I havent tried CloudFoundry yet. It could be something specific to how their http router works. Try making sure it is using port 4443?

**Comment by cireme** [comment]
I also have an echo issue. I'm not testing in the same room.

As I talk I can hear myself talking. 

Are audio and video send inside the same stream ?

**Comment by arzynik** [comment]
a/v are in the same stream

can you try adding `muted` to the local stream element as they mention here? https://stackoverflow.com/questions/18406193/how-to-avoid-echo-and-noise-in-javascript-for-webrtc

should be in `src/components/call-modal/call-modal.html`

if this works for you i will add it to the next release.

**Comment by cireme** [comment]
It works for me. No more echo.

Thanks for your quick answer.

**Comment by arzynik** [comment]
Released in 2.2.1 available at https://market.ionic.io/starters/whatsapp-viber-video-text-chat-full-app
