### ISSUE TITLE
app unable to connect to server 

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [devin-la/ionic-video-chat-v2-issues#69]
polling-xhr.js:261 GET http://192.168.0.214:9000/socket.io/?EIO=3&transport=polling&t=Ljf7dSY net::ERR_CONNECTION_TIMED_OUT

and where to register user isee just a blank window with account title

**Comment by arzynik** [comment]
> polling-xhr.js:261 GET http://192.168.0.214:9000/socket.io/?EIO=3&transport=polling&t=Ljf7dSY net::ERR_CONNECTION_TIMED_OUT

Make sure you are changing your socket server address to the server you setup.
- For v1, that is in `www/js/services/socket.js`
- For v2 that is in `src/app/config.js`

> and where to register user isee just a blank window with account title

What you are seeing is a result above your previous error. Once you fix that error, you will see a login as the main page instead.

**Comment by sidharth016** [comment]
Request URL:http://192.168.0.103:5000/socket.io/?EIO=3&transport=polling&t=LonvBA9
Request Method:GET
Status Code:404 Not Found (from disk cache)
On web works for me, on android when i inspect using chrome device inspector, the polling is unable to connect.
