### ISSUE TITLE
Building Errors

### ISSUE THREAD

**Issue by omkarreddydodda** [devin-la/ionic-video-chat-v2-issues#80]
When am trying to build application on IOS am getting multiple errors how to resolve those swift errors.

**Comment by arzynik** [comment]
what errors?

**Comment by arzynik** [comment]
i think the only swift packages are in iosrtc. You can take a look at this https://github.com/devin-la/ionic-video-chat-v2-issues/wiki/Building#ios which should help.

Basically just dont convert your swift syntax and you should be good. If you already did, remove everything and start over form the archive zip.

**Comment by arapocket** [comment]
Not converting to swift results in build failed! Now what?
