### ISSUE TITLE
IOS video issue

### ISSUE THREAD

**Issue by ProximaHaiz** [devin-la/ionic-video-chat-v2-issues#81]
Hi,  When I run the application on the ios 10.3, and start videochat, the connection is established, but both videos do not start playing. After reading the documentation iosRTC, found a solution in this  
https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/blob/master/docs/iosrtc.md#iosrtcobservevideovideo . 
But there was a following problem, I can not appropriate CSS styles or CSS class for video. tried to do as follows

         `
           let video = document.createElement('video');
            video.classList.add('remote-video');

            cordova.plugins.iosrtc.observeVideo(video);

            video.src = URL.createObjectURL(event.stream);

            video.addEventListener('canplay', function () {
                document.getElementById('videoContainer').appendChild(
            });`
or
          `        

            let video = document.createElement('video');
            video.setAttribute('id', 'remote-video-stream')
            video.setAttribute('position', 'position')
            video.setAttribute('z-index', '-2')
            video.setAttribute('display', 'block')
            video.setAttribute('pointer-events', 'none')
            video.setAttribute('opacity', '1')
            video.setAttribute('object-fit', 'cover')
            video.setAttribute('top', '0')
            video.setAttribute('right', '0')
            video.setAttribute('margin-top', '46px')
            video.setAttribute('width', '100%')

           cordova.plugins.iosrtc.observeVideo(video);

            // Attach the MediaStream to it.
            video.src = URL.createObjectURL(event.
            video.addEventListener('canplay',  ()=> {
                document.getElementById('videoContainer').appendChild(
            });`

but it does not work.
Can you know any solutions or can you give advice on how to assign CSS styles for video elements with this implementation?

**Comment by arzynik** [comment]
the html video element in the page isnt a real video element. its a native element overlayed on top of the page where the video element sits.

you can change the supported properties in the `src/app/app.scss` and change `#local` and `#remote` video tags.

for more info on how the css is imported, see https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/blob/master/docs/videoCSS.md
