### ISSUE TITLE
webPack.Jsonp is not defined

### ISSUE THREAD

**Issue by mfossel** [devin-la/ionic-video-chat-v2-issues#85]
Hello, I purchased your app and I followed the setup instructions to the best of my ability. After setting up the backend and getting the Ionic app running I am getting the following error when attempting to view the app.

`Runtime Error
webpackJsonp is not defined
Stack
ReferenceError: webpackJsonp is not defined
    at http://live-feed-demo-maxhoa.c9users.io:8081/build/main.js:1:1
Ionic Framework: ^2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 2.1.3
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 8.1.0
OS Platform: Linux 4.9
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; CrOS x86_64 9202.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.154 Safari/537.3`

**Comment by mfossel** [comment]
Nevermind, this fixed it.
https://forum.ionicframework.com/t/webpackjsonp-missing-after-ionic-3-update/99582/9

**Comment by npnlab** [comment]
But after follow these steps (
    rm -rf node_modules
    added <script src="build/vendor.js"></script> in index.html
    npm install -g ionic@latest
    npm install @ionic/app-scripts@latest --save-dev
    npm install ionic-angular@latest --save
    npm upgrade for upgrade all modules.
), I get new error:
> Typescript Error
> Initializers are not allowed in ambient contexts.

**Comment by npnlab** [comment]
Ionic Framework: ^3.6.0
Ionic Native: 2.4.1
Ionic App Scripts: 2.1.3
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.9.0
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
