### ISSUE TITLE
Ionic3 install ?

### ISSUE THREAD

**Issue by booradleys** [devin-la/ionic-video-chat-v2-issues#89]
Hi Devin,
Following commands are not valid anymore:

ionic state restore
ionic resources

How can i install package in Ionic 3 ?

**Comment by booradleys** [comment]
Does anyone can help me?

**Comment by arzynik** [comment]
you can youse `ionic cordova prepare` but `npm install` should handle most of what state used to now.

resources is part of cordova, and you can do `ionic cordova resources`
